build:
  stage: test
    - scan-build make
  stage: build
  # instead of calling g++ directly you can also use some build toolkit like make
  # install the necessary build tools when needed
  # before_script: 
  #   - apt update && apt -y install make autoconf 
  script: 
    - make
  artifacts:
    paths:
      - mybinary